# output_dir: experiments/${project}/${name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
output_dir: experiments/${project}/${name}

project: mask-based-wpd_doa-aware-lstm_LibriMixDemandTest
# name: n_spks=2_room_size=middle_rt60=0.5_noise-snr=60.0_src-distance=1.5
name: null

debug: False
testonly: True
ckpt_path: /home/fujita/research/NeuralBF-IROS2022/experiments/LibriMixDemandDual2sec7ch/mask-based-wpd_doa-aware-lstm/2024-07-03-13-06-05/epoch=9-step=90000.ckpt

n_gpus: 1

data_module:
  _target_: src.dataset.doa_aware_test_asr_dataset.LightningDataModule

  batch_size: 1
  num_workers: 3
  n_gpus: ${n_gpus}

  tt_path: /n/work1/fujita/json/libri_mix_demand_test_${name}.json

  tt_size: -1

lightning_module:
  _target_: src.modules.mask_based_wpd.MaskBasedWPD

  eval_asr: True

  delay: 3
  tap: 5

  mask_estimator:
    _target_: src.models.doa_aware_lstm.DOAAwareLSTM
    n_mics: 7
    n_freq: 513 
    input_lstm: 1024
    hidden_lstm: 512
    n_layer: 3

trainer:
  devices: ${n_gpus}
  accelerator: auto
  # strategy: ddp
  precision: 64
  default_root_dir: ${output_dir}

logger: 
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${output_dir}

hydra: 
  run: 
    dir: ${output_dir}