output_dir: experiments/${project}/${name}_total_s=${data_module.total_s}

project: iter_wpe_fastmnmf_LibriMixDemandTest
name: null

debug: False
testonly: True

n_gpus: 1

data_module:
  _target_: src.dataset.doa_aware_adapt_fastmnmf_asr_dataset.LightningDataModule

  batch_size: 1
  num_workers: 3
  n_gpus: ${n_gpus}

  json_path: /n/work1/fujita/json/libri_mix_demand_test_${name}.json
  manifest_path: /n/work1/fujita/manifest/libri_mix_demand_dual_2sec_20h_7ch_train.manifest

  total_s: null

  size: -1

lightning_module:
  _target_: src.modules.iter_wpe_fastmnmf.IterWPEFastMNMF

  eval_asr: True

  delay: 3
  tap: 5
  n_srcs: 2

trainer:
  devices: ${n_gpus}
  accelerator: auto
  # strategy: ddp
  precision: 64
  default_root_dir: ${output_dir}

logger: 
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${output_dir}

hydra: 
  run: 
    dir: ${output_dir}