output_dir: experiments/${project}/${name}

project: fastmnmf_LibriMixDemandTest
name: null

debug: False
testonly: True

n_gpus: 1

data_module:
  _target_: src.dataset.doa_aware_test_asr_dataset.LightningDataModule

  batch_size: 1
  num_workers: 3
  n_gpus: ${n_gpus}

  tt_path: /n/work1/fujita/json/libri_mix_demand_test_${name}.json

  tt_size: -1

lightning_module:
  _target_: src.modules.fastmnmf.FastMNMF

  eval_asr: True

  delay: 3
  tap: 5

  n_srcs: null

  mask_estimator:
    _target_: src.models.doa_aware_lstm.DOAAwareLSTM
    n_mics: 7
    n_freq: 513 
    input_lstm: 1024
    hidden_lstm: 512
    n_layer: 3

trainer:
  devices: ${n_gpus}
  accelerator: auto
  # strategy: ddp
  precision: 64
  default_root_dir: ${output_dir}

logger: 
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${output_dir}

hydra: 
  run: 
    dir: ${output_dir}